version: ">= 0.13.0, < 1.1.0"

formatter: "markdown table"

header-from: main.tf
footer-from: ""

sections:
  #hide: []
  show:
    - data-sources
    - header
    - footer
    - inputs
    - modules
    - outputs
    - providers
    - requirements
    - resources

content: |-
  {{ .Header }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Modules }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Requirements }}

  ## Development

  - This project uses [Semantic Versioning](https://semver.org/).

  ## Examples

  ```hcl
  {{ include "examples/docs/main.tf" }}
  ```

output:
  file: README.md
  mode: inject

sort:
  enabled: true
  by: name

settings:
  anchor: false
  color: true
  default: true
  description: true
  escape: true
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true
